# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

export CONFIG_QTI_HW_FENCE=y
export CONFIG_QTI_HW_FENCE_USE_SYNX=y
export CONFIG_QTI_ENABLE_HW_FENCE_DEFAULT=y
export CONFIG_QTI_HW_FENCE_GFX_DISABLE=y
export CONFIG_QCOM_SPEC_SYNC=y
export CONFIG_QTI_HFI_CORE=y

