# SPDX-License-Identifier: GPL-2.0-only

include $(MM_ROOT)/config/gki_sundisp.conf
LINUXINCLUDE += -include $(MM_ROOT)/config/gki_sundispconf.h \
		-I$(MM_ROOT)/msm_ext_display/include/

obj-m += msm_ext_display.o

msm_ext_display-y := src/msm_ext_display.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
EXTRA_CFLAGS += -Wformat-extra-args -Wstrict-prototypes -Wformat-insufficient-args \
		-Wformat-invalid-specifier -Wformat-zero-length -Wnonnull