# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(CONFIG_ARCH_PEBBLE), y)
	include $(MSM_EXT_DISPLAY_ROOT)config/pebblemmdrivers.conf
	LINUXINCLUDE += -include $(MSM_EXT_DISPLAY_ROOT)config/pebblemmdriversconf.h \
			-I$(MSM_EXT_DISPLAY_ROOT)msm_ext_display/include/
else
	include $(MSM_EXT_DISPLAY_ROOT)/config/kalamammdrivers.conf
	LINUXINCLUDE += -include $(MSM_EXT_DISPLAY_ROOT)/config/kalamammdriversconf.h \
			-I$(MSM_EXT_DISPLAY_ROOT)msm_ext_display/include/
endif

obj-m += msm_ext_display.o

msm_ext_display-y := src/msm_ext_display.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
EXTRA_CFLAGS += -Wformat-extra-args -Wstrict-prototypes -Wformat-insufficient-args \
		-Wformat-invalid-specifier -Wformat-zero-length -Wnonnull
